// <auto-generated />
namespace Vjezba.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initialđ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialđ));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171020146_Initialđ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
