//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vjezba.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbes
    {
        public int ID { get; set; }
        public Nullable<int> KupacId { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> DucaniId { get; set; }
        public Nullable<int> ProdavacId { get; set; }
        public int cijena { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Ducanis Ducanis { get; set; }
        public virtual Kupacs Kupacs { get; set; }
        public virtual Prodavacs Prodavacs { get; set; }
    }
}
